# Generated by Django 3.0.7 on 2020-09-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_website', '0002_auto_20200913_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdata',
            old_name='full_name',
            new_name='first_name',
        ),
    ]
