# Generated by Django 3.0.7 on 2020-09-26 09:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_website', '0003_auto_20200926_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 9, 21, 6, 17854, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1 ->Active, 0->Inactive', null=True),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 26, 9, 21, 6, 17854, tzinfo=utc), null=True),
        ),
    ]
