# Generated by Django 3.0.7 on 2020-09-26 11:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_website', '0005_auto_20200926_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 11, 36, 0, 528067, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 26, 11, 36, 0, 528067, tzinfo=utc), null=True),
        ),
    ]
