# Generated by Django 3.0.7 on 2020-09-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_website', '0007_auto_20200926_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='subject_name',
            field=models.CharField(default=2, max_length=60),
            preserve_default=False,
        ),
    ]
