# Generated by Django 3.0.7 on 2020-09-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_website', '0009_auto_20200926_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='created_on',
            field=models.DateTimeField(default='django utilis.timezone.now()'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1 ->Active, 0->Inactive', null=True),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='updated_on',
            field=models.DateTimeField(blank=True, default='django utilis.timezone.now()', null=True),
        ),
    ]
