# Generated by Django 3.0.7 on 2020-09-27 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_website', '0015_auto_20200927_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 9, 57, 34, 18871)),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 27, 9, 57, 34, 18871), null=True),
        ),
    ]
