# Generated by Django 3.0.7 on 2020-09-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_website', '0022_auto_20200927_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdata',
            name='updated_on',
        ),
    ]
