# Generated by Django 3.0.7 on 2020-09-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_website', '0023_remove_registrationdata_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdata',
            name='created_on',
        ),
    ]
